version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # avoid conflicts with host
    container_name: fruit-frontend-dev
    environment:
      - VITE_API_URL=http://backend:5000  # only needed if backend runs too
